/**
 * Built-in Baan C / Infor LN functions for completions and hovers.
 * Sourced from the official programming guide (string ops, DB, messages, dates, etc.).
 * insertText may be a plain string or use $0 for cursor placement after '('.
 *
 * @typedef {{ name: string, detail: string, doc?: string, insert?: string }} BuiltinFn
 */

/** @type {BuiltinFn[]} */
const BUILTIN_FUNCTIONS = [
  // ── Transactions / DB core ──────────────────────────────────────────
  { name: 'commit.transaction', detail: 'long · commit DB transaction', doc: '```baanc\nlong commit.transaction()\n```\nCommit the current database transaction.', insert: 'commit.transaction()' },
  { name: 'abort.transaction', detail: 'long · abort DB transaction', doc: '```baanc\nlong abort.transaction()\n```\nAbort (roll back) the current database transaction.', insert: 'abort.transaction()' },
  { name: 'db.retry.point', detail: 'void · set retry point', doc: '```baanc\nvoid db.retry.point()\n```\nMark a retry point for transaction recovery after lock conflicts.', insert: 'db.retry.point()' },
  { name: 'db.retry.hit', detail: 'long · retry hit status', insert: 'db.retry.hit()' },
  { name: 'db.max.retry', detail: 'long · max retry count', insert: 'db.max.retry()' },
  { name: 'set.transaction.readonly', detail: 'long · readonly transaction', insert: 'set.transaction.readonly()' },
  { name: 'db.set.error.bypass.on', detail: 'long · enable error bypass', insert: 'db.set.error.bypass.on()' },
  { name: 'db.set.error.bypass.off', detail: 'void · disable error bypass', insert: 'db.set.error.bypass.off()' },
  { name: 'db.get.error.bypass', detail: 'boolean · error bypass state', insert: 'db.get.error.bypass()' },
  { name: 'db.error', detail: 'long · last DB error code', insert: 'db.error()' },
  { name: 'db.error.message', detail: 'string · last DB error text', insert: 'db.error.message()' },
  { name: 'db.flush', detail: 'long · flush DB buffers', insert: 'db.flush()' },

  // ── Low-level table I/O ─────────────────────────────────────────────
  { name: 'db.bind', detail: 'long · bind table buffer', doc: '```baanc\nlong db.bind(string table_name(9) [, ref string buffer(.) [, long comp_nr]])\n```', insert: 'db.bind(${1:table})$0' },
  { name: 'db.unbind', detail: 'long · unbind table', insert: 'db.unbind(${1:table_id})$0' },
  { name: 'db.insert', detail: 'long · insert record', insert: 'db.insert(${1:table_id})$0' },
  { name: 'db.update', detail: 'long · update record', insert: 'db.update(${1:table_id})$0' },
  { name: 'db.delete', detail: 'long · delete record', insert: 'db.delete(${1:table_id})$0' },
  { name: 'db.set.to.default', detail: 'long · default field values', insert: 'db.set.to.default(${1:table_id})$0' },
  { name: 'db.first', detail: 'long · first record', insert: 'db.first(${1:table_id})$0' },
  { name: 'db.last', detail: 'long · last record', insert: 'db.last(${1:table_id})$0' },
  { name: 'db.next', detail: 'long · next record', insert: 'db.next(${1:table_id})$0' },
  { name: 'db.prev', detail: 'long · previous record', insert: 'db.prev(${1:table_id})$0' },
  { name: 'db.curr', detail: 'long · current record', insert: 'db.curr(${1:table_id})$0' },
  { name: 'db.eq', detail: 'long · equal key search', insert: 'db.eq(${1:table_id})$0' },
  { name: 'db.ge', detail: 'long · greater-or-equal key', insert: 'db.ge(${1:table_id})$0' },
  { name: 'db.gt', detail: 'long · greater-than key', insert: 'db.gt(${1:table_id})$0' },
  { name: 'db.le', detail: 'long · less-or-equal key', insert: 'db.le(${1:table_id})$0' },
  { name: 'db.lt', detail: 'long · less-than key', insert: 'db.lt(${1:table_id})$0' },
  { name: 'db.change.order', detail: 'long · change index order', insert: 'db.change.order(${1:table_id}, ${2:index_nr})$0' },
  { name: 'db.lock.table', detail: 'long · lock table', insert: 'db.lock.table(${1:table_id})$0' },
  { name: 'db.store.record', detail: 'void · store record copy', insert: 'db.store.record(${1:table_id})$0' },
  { name: 'db.restore.record', detail: 'void · restore record copy', insert: 'db.restore.record(${1:table_id})$0' },
  { name: 'db.record.changed', detail: 'boolean · record dirty?', insert: 'db.record.changed(${1:table_id})$0' },
  { name: 'db.check.row.changed', detail: 'long · row changed check', insert: 'db.check.row.changed(${1:table_id})$0' },
  { name: 'db.check.row.domains', detail: 'long · domain check', insert: 'db.check.row.domains(${1:table_id}, ${2:fld_name})$0' },
  { name: 'db.check.restricted', detail: 'long · restricted check', insert: 'db.check.restricted(${1:table_id}, ${2:mode}, ${3:message})$0' },
  { name: 'db.columns.to.record', detail: 'long · columns → record', insert: 'db.columns.to.record(${1:table_id})$0' },
  { name: 'db.record.to.columns', detail: 'long · record → columns', insert: 'db.record.to.columns(${1:table_id})$0' },
  { name: 'db.permission', detail: 'long · table permission', insert: 'db.permission(${1:table_id})$0' },
  { name: 'db.nr.rows', detail: 'long · row count', insert: 'db.nr.rows(${1:table_id}, ${2:nr_rows})$0' },
  { name: 'db.nr.indices', detail: 'long · index count', insert: 'db.nr.indices(${1:table_id}, ${2:nr_indices})$0' },
  { name: 'db.row.length', detail: 'long · row length', insert: 'db.row.length(${1:table_id}, ${2:row_length})$0' },
  { name: 'db.clear.table', detail: 'long · clear table', insert: 'db.clear.table(${1:table_id})$0' },
  { name: 'db.create.table', detail: 'long · create table', insert: 'db.create.table(${1:table_id})$0' },
  { name: 'db.drop.table', detail: 'long · drop table', insert: 'db.drop.table(${1:table_id})$0' },
  { name: 'db.ref.handle.mode', detail: 'long · reference handle mode', insert: 'db.ref.handle.mode(${1:table_name}, ${2:mode})$0' },
  { name: 'db.get.physical.compnr', detail: 'long · physical company', insert: 'db.get.physical.compnr(${1:tblname}, ${2:logical.compnr})$0' },
  { name: 'skip.io', detail: 'void · skip I/O with message', insert: 'skip.io(${1:mesg})$0' },
  { name: 'abort.io', detail: 'void · abort I/O', insert: 'abort.io()' },
  { name: 'to.key', detail: 'void · set key number', insert: 'to.key(${1:key_number})$0' },
  { name: 'on.main.table', detail: 'void · run on main table', insert: 'on.main.table(${1:function_name})$0' },
  { name: 'with.object.set.do', detail: 'void · iterate object set', insert: 'with.object.set.do(${1:function_name})$0' },
  { name: 'with.old.object.values.do', detail: 'void · old object values', insert: 'with.old.object.values.do(${1:function_name})$0' },
  { name: 'this.dal', detail: 'string · current DAL name', insert: 'this.dal()' },
  { name: 'count.records.in.view', detail: 'long · count view records', insert: 'count.records.in.view()' },
  { name: 'sum.records.in.view', detail: 'void · sum view column', insert: 'sum.records.in.view(${1:column}, ${2:result})$0' },
  { name: 'for.each.record.in.view.do', detail: 'void · view callback', insert: 'for.each.record.in.view.do(${1:callback})$0' },
  { name: 'set.limits.off', detail: 'void · disable limits', insert: 'set.limits.off()' },
  { name: 'restore.rcd.main', detail: 'void · restore main rcd', insert: 'restore.rcd.main(${1:occurrence})$0' },
  { name: 'store.occ.max', detail: 'void · store max occ', insert: 'store.occ.max()' },
  { name: 'store.occ.min', detail: 'void · store min occ', insert: 'store.occ.min()' },

  // ── DAL high-level ──────────────────────────────────────────────────
  { name: 'dal.new.object', detail: 'long · new DAL object', insert: 'dal.new.object(${1:class_name})$0' },
  { name: 'dal.get.object', detail: 'long · get DAL object', insert: 'dal.get.object(${1:class_name}, ${2:lock})$0' },
  { name: 'dal.save.object', detail: 'long · save DAL object', insert: 'dal.save.object(${1:class_name})$0' },
  { name: 'dal.destroy.object', detail: 'long · destroy DAL object', insert: 'dal.destroy.object(${1:class_name})$0' },
  { name: 'dal.change.object', detail: 'long · change DAL object', insert: 'dal.change.object(${1:class_name})$0' },
  { name: 'dal.copy.object', detail: 'long · copy DAL object', insert: 'dal.copy.object(${1:class_name})$0' },
  { name: 'dal.set.field', detail: 'void · set DAL field', insert: 'dal.set.field(${1:fld_name}, ${2:value})$0' },
  { name: 'dal.check.field', detail: 'long · check DAL field', insert: 'dal.check.field(${1:fld_name})$0' },
  { name: 'dal.is.field.changed', detail: 'boolean · field changed?', insert: 'dal.is.field.changed(${1:fld.name})$0' },
  { name: 'dal.get.field.mode', detail: 'long · field mode', insert: 'dal.get.field.mode(${1:fld_name})$0' },
  { name: 'dal.set.message', detail: 'void · DAL message', insert: 'dal.set.message(${1:msg})$0' },
  { name: 'dal.set.error.message', detail: 'void · DAL error message', insert: 'dal.set.error.message(${1:msg})$0' },
  { name: 'dal.clear.messages', detail: 'void · clear DAL messages', insert: 'dal.clear.messages()' },
  { name: 'dal.clear.error.messages', detail: 'void · clear DAL errors', insert: 'dal.clear.error.messages()' },
  { name: 'dal.start.business.method', detail: 'void · business method', insert: 'dal.start.business.method(${1:set_id}, ${2:name}, ${3:retval})$0' },
  { name: 'dal.submit', detail: 'long · submit workflow', insert: 'dal.submit(${1:tbl.name})$0' },
  { name: 'dal.recall', detail: 'long · recall workflow', insert: 'dal.recall(${1:tbl.name})$0' },
  { name: 'dal.reject', detail: 'long · reject workflow', insert: 'dal.reject(${1:tbl.name}, ${2:reason$})$0' },

  // ── Messages / UI feedback ──────────────────────────────────────────
  { name: 'message', detail: 'void · show message', doc: '```baanc\nmessage(string text [, ...])\n```\nDisplay a message (supports sprintf-style placeholders).', insert: 'message("${1:text}")$0' },
  { name: 'mess', detail: 'void · message by code', doc: '```baanc\nmess(string code [, ...])\n```\nShow a dictionary message by code.', insert: 'mess("${1:code}")$0' },
  { name: 'status.mess', detail: 'void · status bar message', insert: 'status.mess("${1:text}")$0' },
  { name: 'status.del', detail: 'void · clear status message', insert: 'status.del()' },
  { name: 'clean.mess', detail: 'void · clear messages', insert: 'clean.mess()' },
  { name: 'form.text', detail: 'void · form text area', insert: 'form.text(${1:text})$0' },
  { name: 'set.input.error', detail: 'void · mark input error', insert: 'set.input.error(${1:mesg})$0' },
  { name: 'show.dal.messages', detail: 'void · show DAL messages', insert: 'show.dal.messages()' },
  { name: 'add.message.button', detail: 'void · message button', insert: 'add.message.button(${1:label})$0' },

  // ── String operations ───────────────────────────────────────────────
  { name: 'strip$', detail: 'string · strip trailing spaces', doc: '```baanc\nstring strip$(string strg(.))\n```\nRemove trailing spaces from a string.', insert: 'strip$(${1:str})$0' },
  { name: 'trim$', detail: 'string · trim whitespace', insert: 'trim$(${1:str})$0' },
  { name: 'shiftl$', detail: 'string · shift left', insert: 'shiftl$(${1:str})$0' },
  { name: 'shiftr$', detail: 'string · shift right', insert: 'shiftr$(${1:str})$0' },
  { name: 'shiftc$', detail: 'string · center string', insert: 'shiftc$(${1:str})$0' },
  { name: 'tolower$', detail: 'string · to lower case', insert: 'tolower$(${1:str})$0' },
  { name: 'toupper$', detail: 'string · to upper case', insert: 'toupper$(${1:str})$0' },
  { name: 'str$', detail: 'string · number → string', doc: '```baanc\nstring str$(num_expr)\n```\nConvert a number to string.', insert: 'str$(${1:num})$0' },
  { name: 'val', detail: 'double · string → double', insert: 'val(${1:str})$0' },
  { name: 'lval', detail: 'long · string → long', insert: 'lval(${1:str})$0' },
  { name: 'len', detail: 'long · string length', insert: 'len(${1:str})$0' },
  { name: 'len.in.bytes', detail: 'long · byte length', insert: 'len.in.bytes(${1:str})$0' },
  { name: 'pos', detail: 'long · find substring', doc: '```baanc\nlong pos(string source, string pattern[, long offset])\n```', insert: 'pos(${1:source}, ${2:pattern})$0' },
  { name: 'rpos', detail: 'long · find last substring', insert: 'rpos(${1:source}, ${2:pattern})$0' },
  { name: 'str_pos', detail: 'long · find substring (alt)', insert: 'str_pos(${1:source}, ${2:pattern})$0' },
  { name: 'str_rpos', detail: 'long · find last (alt)', insert: 'str_rpos(${1:source}, ${2:pattern})$0' },
  { name: 'concat$', detail: 'string · join with separator', insert: 'concat$(${1:sep}, ${2:expr})$0' },
  { name: 'isdigit', detail: 'boolean · all digits?', insert: 'isdigit(${1:str})$0' },
  { name: 'isspace', detail: 'boolean · all spaces?', insert: 'isspace(${1:str})$0' },
  { name: 'string.set$', detail: 'string · repeat char/string', insert: 'string.set$(${1:expr}, ${2:n})$0' },
  { name: 'str.equals', detail: 'boolean · string equal?', insert: 'str.equals(${1:a$}, ${2:b$})$0' },
  { name: 'str.compare', detail: 'long · compare strings', insert: 'str.compare(${1:a$}, ${2:b$})$0' },
  { name: 'str.startswith', detail: 'boolean · starts with?', insert: 'str.startswith(${1:string$}, ${2:part$})$0' },
  { name: 'str.endswith', detail: 'boolean · ends with?', insert: 'str.endswith(${1:string$}, ${2:part$})$0' },
  { name: 'str.substring$', detail: 'string · substring', insert: 'str.substring$(${1:string$}, ${2:beginpos})$0' },
  { name: 'str.replace$', detail: 'string · replace all', insert: 'str.replace$(${1:string$}, ${2:old$}, ${3:new$})$0' },
  { name: 'str.replace', detail: 'void · replace into ref', insert: 'str.replace(${1:string$}, ${2:old$}, ${3:new$}, ${4:result$})$0' },
  { name: 'str.insert$', detail: 'string · insert part', insert: 'str.insert$(${1:string$}, ${2:offset}, ${3:part$})$0' },
  { name: 'str.remove$', detail: 'string · remove part', insert: 'str.remove$(${1:string$}, ${2:offset}, ${3:nchars})$0' },
  { name: 'str.join$', detail: 'string · join parts', insert: 'str.join$(${1:separator$})$0' },
  { name: 'str.split', detail: 'long · split string', insert: 'str.split(${1:string$}, ${2:sep$}, ${3:limit}, ${4:parts})$0' },
  { name: 'str.assign', detail: 'void · assign string', insert: 'str.assign(${1:target$}, ${2:source$})$0' },
  { name: 'str.alloc', detail: 'void · allocate string', insert: 'str.alloc(${1:string$}, ${2:nchars})$0' },
  { name: 'str.sizeof', detail: 'long · allocated size', insert: 'str.sizeof(${1:string$})$0' },
  { name: 'str.unquote$', detail: 'string · unquote', insert: 'str.unquote$(${1:string$})$0' },
  { name: 'not.fixed', detail: 'void · make string not fixed', insert: 'not.fixed(${1:string_var})$0' },
  { name: 'tt.align.according.domain', detail: 'long · align by domain', insert: 'tt.align.according.domain(${1:in}, ${2:out}, ${3:domain})$0' },
  { name: 'string.to.bounded.long', detail: 'long · parse bounded long', insert: 'string.to.bounded.long(${1:string$}, ${2:lo}, ${3:hi})$0' },

  // ── Formatting I/O ──────────────────────────────────────────────────
  { name: 'sprintf', detail: 'string · format string', doc: '```baanc\nsprintf(format, ...)\n```\nPrintf-style string formatting.', insert: 'sprintf("${1:%s}", ${2:arg})$0' },
  { name: 'vsprintf', detail: 'string · format (va_list style)', insert: 'vsprintf(${1:format}, ${2:args})$0' },
  { name: 'edit$', detail: 'string · edit/format value', insert: 'edit$(${1:value}, ${2:format})$0' },
  { name: 'string.scan', detail: 'long · scan string', insert: 'string.scan(${1:source}, ${2:format})$0' },

  // ── Date / time ─────────────────────────────────────────────────────
  { name: 'date.num', detail: 'long · current date number', insert: 'date.num()' },
  { name: 'time.num', detail: 'long · current time number', insert: 'time.num()' },
  { name: 'utc.num', detail: 'long · current UTC number', insert: 'utc.num()' },
  { name: 'dte$', detail: 'string · format date', insert: 'dte$(${1:date.num})$0' },
  { name: 'date.to.num', detail: 'long · date parts → num', insert: 'date.to.num(${1:year}, ${2:month}, ${3:day})$0' },
  { name: 'num.to.date', detail: 'void · num → date parts', insert: 'num.to.date(${1:date.num}, ${2:year}, ${3:month}, ${4:day})$0' },
  { name: 'num.to.dates', detail: 'string · num → date string', insert: 'num.to.dates(${1:date.num})$0' },
  { name: 'date.to.utc', detail: 'long · date → UTC', insert: 'date.to.utc(${1:date})$0' },
  { name: 'utc.to.date', detail: 'void · UTC → date', insert: 'utc.to.date(${1:utc})$0' },
  { name: 'utc.to.local', detail: 'long · UTC → local', insert: 'utc.to.local(${1:utc})$0' },
  { name: 'local.to.utc', detail: 'long · local → UTC', insert: 'local.to.utc(${1:local})$0' },
  { name: 'utc.add', detail: 'long · add to UTC', insert: 'utc.add(${1:utc}, ${2:amount}, ${3:unit})$0' },
  { name: 'week.to.num', detail: 'long · week → date num', insert: 'week.to.num(${1:week}, ${2:year}, ${3:day})$0' },
  { name: 'num.to.week', detail: 'void · date → week', insert: 'num.to.week(${1:date.num}, ${2:week}, ${3:year})$0' },
  { name: 'utc.to.week', detail: 'void · UTC → week', insert: 'utc.to.week(${1:utc}, ${2:week}, ${3:year})$0' },
  { name: 'week.to.utc', detail: 'long · week → UTC', insert: 'week.to.utc(${1:week}, ${2:year}, ${3:day})$0' },
  { name: 'date.to.iso', detail: 'string · date → ISO', insert: 'date.to.iso(${1:date})$0' },
  { name: 'iso.to.date', detail: 'long · ISO → date', insert: 'iso.to.date(${1:iso$})$0' },
  { name: 'utc.to.iso', detail: 'string · UTC → ISO', insert: 'utc.to.iso(${1:utc})$0' },
  { name: 'iso.to.utc', detail: 'long · ISO → UTC', insert: 'iso.to.utc(${1:iso$})$0' },
  { name: 'get.time.zone', detail: 'string · current time zone', insert: 'get.time.zone()' },
  { name: 'set.time.zone', detail: 'long · set time zone', insert: 'set.time.zone(${1:zone$})$0' },

  // ── Math ────────────────────────────────────────────────────────────
  { name: 'abs', detail: 'number · absolute value', insert: 'abs(${1:x})$0' },
  { name: 'min', detail: 'number · minimum', insert: 'min(${1:a}, ${2:b})$0' },
  { name: 'max', detail: 'number · maximum', insert: 'max(${1:a}, ${2:b})$0' },
  { name: 'sqrt', detail: 'double · square root', insert: 'sqrt(${1:x})$0' },
  { name: 'pow', detail: 'double · power', insert: 'pow(${1:base}, ${2:exp})$0' },
  { name: 'lpow', detail: 'long · long power', insert: 'lpow(${1:base}, ${2:exp})$0' },
  { name: 'exp', detail: 'double · e^x', insert: 'exp(${1:x})$0' },
  { name: 'log', detail: 'double · natural log', insert: 'log(${1:x})$0' },
  { name: 'log10', detail: 'double · log base 10', insert: 'log10(${1:x})$0' },
  { name: 'sin', detail: 'double · sine', insert: 'sin(${1:x})$0' },
  { name: 'cos', detail: 'double · cosine', insert: 'cos(${1:x})$0' },
  { name: 'tan', detail: 'double · tangent', insert: 'tan(${1:x})$0' },
  { name: 'asin', detail: 'double · arcsin', insert: 'asin(${1:x})$0' },
  { name: 'acos', detail: 'double · arccos', insert: 'acos(${1:x})$0' },
  { name: 'atan', detail: 'double · arctan', insert: 'atan(${1:x})$0' },
  { name: 'sinh', detail: 'double · hyperbolic sine', insert: 'sinh(${1:x})$0' },
  { name: 'cosh', detail: 'double · hyperbolic cosine', insert: 'cosh(${1:x})$0' },
  { name: 'tanh', detail: 'double · hyperbolic tan', insert: 'tanh(${1:x})$0' },
  { name: 'round', detail: 'double · round', insert: 'round(${1:x}, ${2:digits})$0' },
  { name: 'format.round', detail: 'double · format round', insert: 'format.round(${1:x}, ${2:format})$0' },
  { name: 'table.round', detail: 'double · table round', insert: 'table.round(${1:x})$0' },
  { name: 'halfadj', detail: 'double · half adjust', insert: 'halfadj(${1:x})$0' },
  { name: 'int', detail: 'long · truncate to int', insert: 'int(${1:x})$0' },
  { name: 'double.cmp', detail: 'long · compare doubles', insert: 'double.cmp(${1:a}, ${2:b})$0' },
  { name: 'set.min', detail: 'void · track minimum', insert: 'set.min(${1:var}, ${2:value})$0' },
  { name: 'set.max', detail: 'void · track maximum', insert: 'set.max(${1:var}, ${2:value})$0' },
  { name: 'set.fmin', detail: 'void · track min (float)', insert: 'set.fmin(${1:var}, ${2:value})$0' },
  { name: 'set.fmax', detail: 'void · track max (float)', insert: 'set.fmax(${1:var}, ${2:value})$0' },

  // ── Boolean / ASCII ─────────────────────────────────────────────────
  { name: 'btol', detail: 'long · boolean → long', insert: 'btol(${1:b})$0' },
  { name: 'ltob', detail: 'boolean · long → boolean', insert: 'ltob(${1:n})$0' },
  { name: 'asc', detail: 'long · char → ASCII code', insert: 'asc(${1:ch})$0' },
  { name: 'chr$', detail: 'string · ASCII → char', insert: 'chr$(${1:code})$0' },

  // ── Enumerates ──────────────────────────────────────────────────────
  { name: 'enum.descr$', detail: 'string · enum description', insert: 'enum.descr$(${1:domain}, ${2:value})$0' },
  { name: 'etol', detail: 'long · enum → long', insert: 'etol(${1:enum.val})$0' },
  { name: 'ltoe', detail: 'domain · long → enum', insert: 'ltoe(${1:domain}, ${2:n})$0' },
  { name: 'ask.enum', detail: 'domain · ask enum value', insert: 'ask.enum(${1:domain})$0' },
  { name: 'set.enum.values', detail: 'void · set enum values', insert: 'set.enum.values(${1:domain})$0' },
  { name: 'set.enum.values.for.field', detail: 'void · enum values for field', insert: 'set.enum.values.for.field(${1:field})$0' },

  // ── Import / export / variables ─────────────────────────────────────
  { name: 'export', detail: 'long · export variable', doc: '```baanc\nexport(string name, value)\n```\nExport a variable to another process/session.', insert: 'export("${1:name}", ${2:value})$0' },
  { name: 'import', detail: 'long · import variable', insert: 'import("${1:name}", ${2:var})$0' },
  { name: 'get.var', detail: 'long · get variable by name', insert: 'get.var(${1:process}, "${2:name}", ${3:var})$0' },
  { name: 'put.var', detail: 'long · put variable by name', insert: 'put.var(${1:process}, "${2:name}", ${3:value})$0' },
  { name: 'get.indexed.var', detail: 'long · get indexed var', insert: 'get.indexed.var(${1:process}, "${2:name}", ${3:index}, ${4:var})$0' },
  { name: 'put.indexed.var', detail: 'long · put indexed var', insert: 'put.indexed.var(${1:process}, "${2:name}", ${3:index}, ${4:value})$0' },
  { name: 'import.4gl.var', detail: 'long · import 4GL var', insert: 'import.4gl.var("${1:name}", ${2:var})$0' },

  // ── Form / field UI ─────────────────────────────────────────────────
  { name: 'display', detail: 'void · display field(s)', insert: 'display(${1:field})$0' },
  { name: 'display.all', detail: 'void · display all fields', insert: 'display.all()' },
  { name: 'display.fld', detail: 'void · display field', insert: 'display.fld(${1:field})$0' },
  { name: 'display.occ', detail: 'void · display occurrence', insert: 'display.occ(${1:occ})$0' },
  { name: 'display.curr.occ', detail: 'void · display current occ', insert: 'display.curr.occ()' },
  { name: 'update.occ', detail: 'void · update occurrence', insert: 'update.occ()' },
  { name: 'refresh.curr.occ', detail: 'void · refresh current occ', insert: 'refresh.curr.occ()' },
  { name: 'refresh.all.occs', detail: 'void · refresh all occs', insert: 'refresh.all.occs()' },
  { name: 'enable.fields', detail: 'void · enable fields', insert: 'enable.fields(${1:field})$0' },
  { name: 'disable.fields', detail: 'void · disable fields', insert: 'disable.fields(${1:field})$0' },
  { name: 'inputfield.invisible', detail: 'void · hide field', insert: 'inputfield.invisible(${1:field})$0' },
  { name: 'inputfield.visible', detail: 'void · show field', insert: 'inputfield.visible(${1:field})$0' },
  { name: 'inputfield.password', detail: 'void · password field', insert: 'inputfield.password(${1:field})$0' },
  { name: 'is.field.invisible', detail: 'boolean · field invisible?', insert: 'is.field.invisible(${1:field})$0' },
  { name: 'to.field', detail: 'void · focus field', insert: 'to.field(${1:field})$0' },
  { name: 'to.form', detail: 'void · go to form', insert: 'to.form(${1:form.nr})$0' },
  { name: 'to.group', detail: 'void · go to group', insert: 'to.group(${1:group})$0' },
  { name: 'get.prev.value', detail: 'void · previous field value', insert: 'get.prev.value(${1:field}, ${2:var})$0' },
  { name: 'set.fields.default', detail: 'void · default field values', insert: 'set.fields.default()' },
  { name: 'check.all.input', detail: 'void · check all input', insert: 'check.all.input()' },
  { name: 'input.again', detail: 'void · re-enter field', insert: 'input.again()' },
  { name: 'choice.again', detail: 'void · choice again', insert: 'choice.again()' },
  { name: 'blank.all', detail: 'void · blank all fields', insert: 'blank.all()' },
  { name: 'execute', detail: 'void · execute choice', insert: 'execute(${1:choice})$0' },
  { name: 'enable.commands', detail: 'void · enable commands', insert: 'enable.commands(${1:cmd})$0' },
  { name: 'disable.commands', detail: 'void · disable commands', insert: 'disable.commands(${1:cmd})$0' },
  { name: 'do.occ', detail: 'void · for each occ', insert: 'do.occ(${1:function})$0' },
  { name: 'do.all.occ', detail: 'void · all occurrences', insert: 'do.all.occ(${1:function})$0' },
  { name: 'make.current', detail: 'void · make occ current', insert: 'make.current(${1:occ})$0' },
  { name: 'mark.occ', detail: 'void · mark occurrence', insert: 'mark.occ(${1:occ})$0' },
  { name: 'remove.mark', detail: 'void · remove mark', insert: 'remove.mark()' },
  { name: 'change.field.label', detail: 'void · change field label', insert: 'change.field.label(${1:field}, ${2:label})$0' },
  { name: 'get.field.label', detail: 'string · field label', insert: 'get.field.label(${1:field})$0' },

  // ── Company ─────────────────────────────────────────────────────────
  { name: 'get.compnr', detail: 'long · current company', insert: 'get.compnr()' },
  { name: 'get.company', detail: 'long · current company', insert: 'get.company()' },
  { name: 'switch.to.company', detail: 'long · switch company', insert: 'switch.to.company(${1:compnr})$0' },
  { name: 'compnr.check', detail: 'long · check company', insert: 'compnr.check(${1:compnr})$0' },
  { name: 'get.financial.compnr', detail: 'long · financial company', insert: 'get.financial.compnr()' },
  { name: 'get.logistic.compnr', detail: 'long · logistic company', insert: 'get.logistic.compnr()' },

  // ── System / user ───────────────────────────────────────────────────
  { name: 'bse.dir', detail: 'string · BSE directory', insert: 'bse.dir()' },
  { name: 'bse.tmp.dir', detail: 'string · BSE temp dir', insert: 'bse.tmp.dir()' },
  { name: 'bse.release', detail: 'string · BSE release', insert: 'bse.release()' },
  { name: 'bse.appdata.dir', detail: 'string · appdata dir', insert: 'bse.appdata.dir()' },
  { name: 'hostname', detail: 'string · host name', insert: 'hostname()' },
  { name: 'getenv$', detail: 'string · environment var', insert: 'getenv$(${1:name})$0' },
  { name: 'setenv', detail: 'long · set environment', insert: 'setenv(${1:name}, ${2:value})$0' },
  { name: 'get.os.user', detail: 'string · OS user', insert: 'get.os.user()' },
  { name: 'get.bw.username', detail: 'string · BW username', insert: 'get.bw.username()' },
  { name: 'get.bw.hostname', detail: 'string · BW hostname', insert: 'get.bw.hostname()' },
  { name: 'get.bw.ip.address', detail: 'string · BW IP', insert: 'get.bw.ip.address()' },
  { name: 'is.administrator', detail: 'boolean · admin user?', insert: 'is.administrator()' },
  { name: 'ostype', detail: 'long · OS type', insert: 'ostype()' },
  { name: 'user.exists', detail: 'boolean · user exists?', insert: 'user.exists(${1:user})$0' },
  { name: 'group.exists', detail: 'boolean · group exists?', insert: 'group.exists(${1:group})$0' },
  { name: 'get.resource$', detail: 'string · resource value', insert: 'get.resource$(${1:name})$0' },

  // ── Process ─────────────────────────────────────────────────────────
  { name: 'sleep', detail: 'void · sleep process', insert: 'sleep(${1:ms})$0' },
  { name: 'suspend', detail: 'long · suspend ms', insert: 'suspend(${1:ms})$0' },
  { name: 'activate', detail: 'long · activate process', insert: 'activate(${1:process})$0' },
  { name: 'reactivate', detail: 'long · reactivate process', insert: 'reactivate(${1:process})$0' },
  { name: 'kill', detail: 'long · kill process', insert: 'kill(${1:process})$0' },
  { name: 'wait', detail: 'long · wait for process', insert: 'wait()' },
  { name: 'wait.and.activate', detail: 'long · wait then activate', insert: 'wait.and.activate(${1:process})$0' },
  { name: 'act.and.sleep', detail: 'long · activate and sleep', insert: 'act.and.sleep(${1:process})$0' },
  { name: 'bshell.pid', detail: 'long · bshell process id', insert: 'bshell.pid()' },
  { name: 'argc', detail: 'long · argument count', insert: 'argc()' },
  { name: 'argv', detail: 'string · argument by index', insert: 'argv(${1:n})$0' },
  { name: 'pstat', detail: 'long · process status', insert: 'pstat(${1:process})$0' },

  // ── Bit operations ──────────────────────────────────────────────────
  { name: 'bit.and', detail: 'long · bitwise AND', insert: 'bit.and(${1:a}, ${2:b})$0' },
  { name: 'bit.or', detail: 'long · bitwise OR', insert: 'bit.or(${1:a}, ${2:b})$0' },
  { name: 'bit.exor', detail: 'long · bitwise XOR', insert: 'bit.exor(${1:a}, ${2:b})$0' },
  { name: 'bit.inv', detail: 'long · bitwise NOT', insert: 'bit.inv(${1:a})$0' },
  { name: 'bit.in', detail: 'boolean · bit set?', insert: 'bit.in(${1:bit}, ${2:mask})$0' },
  { name: 'bit.shiftl', detail: 'long · shift left', insert: 'bit.shiftl(${1:value}, ${2:n})$0' },
  { name: 'bit.shiftr', detail: 'long · shift right', insert: 'bit.shiftr(${1:value}, ${2:n})$0' },

  // ── Base64 / misc ───────────────────────────────────────────────────
  { name: 'base64.encode$', detail: 'string · Base64 encode', insert: 'base64.encode$(${1:data})$0' },
  { name: 'base64.decode$', detail: 'string · Base64 decode', insert: 'base64.decode$(${1:data})$0' },
  { name: 'uuid.generate$', detail: 'string · generate UUID', insert: 'uuid.generate$()' },

  // ── Progress ────────────────────────────────────────────────────────
  { name: 'progress.init', detail: 'void · init progress bar', insert: 'progress.init(${1:max})$0' },
  { name: 'progress.set', detail: 'void · set progress', insert: 'progress.set(${1:value})$0' },
  { name: 'progress.stop', detail: 'void · stop progress', insert: 'progress.stop()' },

  // ── Query extensions (common) ───────────────────────────────────────
  { name: 'query.extend.select', detail: 'void · extend SELECT', insert: 'query.extend.select(${1:extension})$0' },
  { name: 'query.extend.from', detail: 'void · extend FROM', insert: 'query.extend.from(${1:extension})$0' },
  { name: 'query.extend.where', detail: 'void · extend WHERE', insert: 'query.extend.where(${1:extension})$0' },
  { name: 'query.extend.where.and', detail: 'void · AND to WHERE', insert: 'query.extend.where.and(${1:extension})$0' },
  { name: 'query.extend.order', detail: 'void · extend ORDER BY', insert: 'query.extend.order(${1:extension})$0' },
  { name: 'query.clear', detail: 'void · clear query extend', insert: 'query.clear()' },

  // ── SQL bind helpers ────────────────────────────────────────────────
  { name: 'selectbind', detail: 'void · bind select :n', insert: 'selectbind(${1:n}, ${2:variable})$0' },
  { name: 'wherebind', detail: 'void · bind where :n', insert: 'wherebind(${1:n}, ${2:expression})$0' },

  // ── Starting sessions ───────────────────────────────────────────────
  { name: 'start.session', detail: 'long · start session', insert: 'start.session(${1:session})$0' },
  { name: 'zoom.to$', detail: 'string · zoom to session', insert: 'zoom.to$(${1:session})$0' },
  { name: 'zoom.to', detail: 'void · zoom to session', insert: 'zoom.to(${1:session})$0' }
];

/** @type {Map<string, BuiltinFn>} */
const BUILTIN_BY_NAME = new Map(
  BUILTIN_FUNCTIONS.map(f => [f.name.toLowerCase(), f])
);

module.exports = {
  BUILTIN_FUNCTIONS,
  BUILTIN_BY_NAME
};
